### ISSUE TITLE
KeyError: 'num_annotations'

### ISSUE THREAD

**Issue by keegen** [sbywater/django-asana#13]
below is the output during **sync_from_asana**

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/root/cr2/cr_env2.1/lib/python3.6/site-packages/Django-2.1.11.dev20190701082148-py3.6.egg/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/cr2/cr_env2.1/lib/python3.6/site-packages/Django-2.1.11.dev20190701082148-py3.6.egg/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/cr2/cr_env2.1/lib/python3.6/site-packages/Django-2.1.11.dev20190701082148-py3.6.egg/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/cr2/cr_env2.1/lib/python3.6/site-packages/Django-2.1.11.dev20190701082148-py3.6.egg/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/root/cr2/cr_env2.1/lib/python3.6/site-packages/djasana/management/commands/sync_from_asana.py", line 91, in handle
    self._sync_workspace_id(workspace_id, projects, models)
  File "/root/cr2/cr_env2.1/lib/python3.6/site-packages/djasana/management/commands/sync_from_asana.py", line 400, in _sync_workspace_id
    self._check_sync_project_id(project_id, workspace, models)
  File "/root/cr2/cr_env2.1/lib/python3.6/site-packages/djasana/management/commands/sync_from_asana.py", line 141, in _check_sync_project_id
    is_archived = self._sync_project_id(project_id, models)
  File "/root/cr2/cr_env2.1/lib/python3.6/site-packages/djasana/management/commands/sync_from_asana.py", line 255, in _sync_project_id
    self._sync_task(task, project, models)
  File "/root/cr2/cr_env2.1/lib/python3.6/site-packages/djasana/management/commands/sync_from_asana.py", line 329, in _sync_task
    self._sync_task(subtask, project, models)
  File "/root/cr2/cr_env2.1/lib/python3.6/site-packages/djasana/management/commands/sync_from_asana.py", line 338, in _sync_task
    sync_attachment(self.client, task_, attachment['id'])
  File "/root/cr2/cr_env2.1/lib/python3.6/site-packages/djasana/utils.py", line 69, in sync_attachment
    attachment_dict.pop('num_annotations')
KeyError: 'num_annotations'

**Comment by sbywater** [comment]
This has been fixed in master but hasn't made it into a point release yet. When we resolve the other issue you've opened, I will tag a new point release. In the mean time you can install the master branch like this:

`pip install https://github.com/sbywater/django-asana/archive/master.tar.gz`

**Comment by keegen** [comment]
when I install using this master and update CustomField in models.py to include is_global_to_workspace the sync works perfectly. thanks!

**Comment by sbywater** [comment]
Thank you for your reports. Fixed in v1.4.1.
