### ISSUE TITLE
custom field raises FieldError when synchronizing

### ISSUE THREAD

**Issue by belgianbluebear** [sbywater/django-asana#18]
env: debian buster + pycharm-pro + pyenv + poetry
auth provider: access-token

Stack:
```
(time-pilot-5C84vnQ3-py3.9) *****@*****:~/*****$ python manage.py sync_from_asana
WARNING: This will irreparably synchronize your local database from Asana.
Are you sure you wish to continue? [y/N] y
Synchronizing data from Asana.
Traceback (most recent call last):
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
djasana.models.DoesNotExist: CustomField matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/*****/PycharmProjects/time_pilot/manage.py", line 22, in <module>
    main()
  File "/home/*****/PycharmProjects/time_pilot/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/djasana/management/commands/sync_from_asana.py", line 90, in handle
    self._sync_workspace_id(workspace_id, projects, models)
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/djasana/management/commands/sync_from_asana.py", line 398, in _sync_workspace_id
    self._check_sync_project_id(project_id, workspace, models)
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/djasana/management/commands/sync_from_asana.py", line 140, in _check_sync_project_id
    is_archived = self._sync_project_id(project_id, models)
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/djasana/management/commands/sync_from_asana.py", line 247, in _sync_project_id
    project = sync_project(self.client, project_dict)
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/djasana/utils.py", line 109, in sync_project
    sync_custom_fields(
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/djasana/utils.py", line 164, in sync_custom_fields
    CustomField.objects.update_or_create(
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/django/db/models/query.py", line 608, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/django/db/models/query.py", line 583, in get_or_create
    params = self._extract_model_params(defaults, **kwargs)
  File "/home/*****/.cache/pypoetry/virtualenvs/time-pilot-5C84vnQ3-py3.9/lib/python3.9/site-packages/django/db/models/query.py", line 634, in _extract_model_params
    raise exceptions.FieldError(
django.core.exceptions.FieldError: Invalid field name(s) for model CustomField: 'created_by'.
```
deps:
'''
[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.9"
whitenoise = "^5.3.0"
django-allauth = "^0.45.0"
django-asana = "^1.4.6"
asana = "^0.10.3"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "^3.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
'''

**Comment by sbywater** [comment]
This is now fixed in v1.4.7 which adds a migration to support this new field. Thank you for your report.
